[[questions]]
question_type_id = "single_answer"
category_id = "video_games"
[[questions.detail]]
text = "Which Pokemon has the lowest total base stats?"
answer = "Shedninja"

[[questions]]
question_type_id = "multiple_answer"
category_id = "video_games"
[[questions.detail]]
text = "Who were the main characters in Donkey Kong Country 3?"
answers = ["Dixie Kong", "Kiddy Kong"]

[[questions]]
question_type_id = "multiple_choice"
category_id = "video_games"
[[questions.detail]]
text = "Which of these courses did not appear in Mario Kart 64?"
choices = ["Kalimari Desert", "Choco Mountain", "Sherbet Land", "Yoshi Circuit"]
answer = ["Yoshi Circuit"]
