[[questions]]
question_type_id = "single_answer"
category_id = "video_games"
[questions.detail]
text = "What is the only Pokemon to have a lower base state total than its pre-evolved form?"
answer = ["Shedninja"]

[[questions]]
question_type_id = "single_answer"
category_id = "video_games"
[questions.detail]
text = "What is the best selling Nintendo 64 game that was never bundled with the console?"
answer = ["Mario Kart 64"]

[[questions]]
question_type_id = "single_answer"
category_id = "video_games"
[questions.detail]
text = "Which Ghost-type Pokemon has the lowest total base stats?"
answer = ["Shedninja"]

[[questions]]
question_type_id = "single_answer"
category_id = "video_games"
[questions.detail]
text = "The Mario series character Toad made their first appearance in which game?"
answer = ["Super Mario Bros. 2", "SMB2"]

[[questions]]
question_type_id = "single_answer"
category_id = "video_games"
[questions.detail]
text = "The Mario series character Toadsworth made their first appearance in which game?"
answer = ["Super Mario Sunshine", "Sunshine", "SMS"]

[[questions]]
question_type_id = "single_answer"
category_id = "video_games"
[questions.detail]
text = "Mario made his first appearance in which game?"
answer = ["Donkey Kong", "DK"]

[[questions]]
question_type_id = "single_answer"
category_id = "video_games"
[questions.detail]
text = "The Mario series character Peach made their first appearance in which game?"
answer = ["Super Mario Bros.", "SMB", "SMB1", "SMB 1"]

[[questions]]
question_type_id = "single_answer"
category_id = "video_games"
[questions.detail]
text = "The Mario series character Peach made their first appearance in which game?"
answer = ["Super Mario Bros.", "SMB", "SMB1", "SMB 1"]

[[questions]]
question_type_id = "single_answer"
category_id = "video_games"
[questions.detail]
text = "What game did Waluigi first appear in?"
answer = ["Mario Tennis"]

[[questions]]
question_type_id = "single_answer"
category_id = "video_games"
[questions.detail]
text = "What is the name of the first Bowser level in Super Mario 64?"
answer = ["Bowser in the Dark World", "BITDW", "Dark World"]

[[questions]]
question_type_id = "single_answer"
category_id = "video_games"
[questions.detail]
text = "In Super Mario Sunshine, a certain mission in what world must you complete before Yoshi is unlocked."
answer = ["Pinna Park"]

[[questions]]
question_type_id = "single_answer"
category_id = "video_games"
[questions.detail]
text = "The name of your boat in The Legend of Zelda: Wind Waker is 'The King of Red ___'?"
answer = ["Lions"]

[[questions]]
question_type_id = "single_answer"
category_id = "video_games"
[questions.detail]
text = "What game did Toadette first appear in?"
answer = ["Mario Kart: Double Dash", "MKDD", "Mario Kart Double Dash"]

[[questions]]
question_type_id = "single_answer"
category_id = "video_games"
[questions.detail]
text = "What was the most recent game to feature Donkey Kong Jr. as a playable character?"
answer = ["Mario Tennis"]
