[[questions]]
question_type_id = "single_answer"
tags = ["video_games"]
[questions.detail]
text = "What is the only Pokemon to have a lower base state total than its pre-evolved form?"
answer = ["Shedinja"]

[[questions]]
question_type_id = "single_answer"
tags = ["video_games"]
[questions.detail]
text = "What is the best selling Nintendo 64 game that was never bundled with the console?"
answer = ["Mario Kart 64"]

[[questions]]
question_type_id = "single_answer"
tags = ["video_games"]
[questions.detail]
text = "Which Ghost-type Pokemon has the lowest total base stats?"
answer = ["Shedinja"]

[[questions]]
question_type_id = "single_answer"
tags = ["video_games"]
[questions.detail]
text = "The Mario series character Toad made their first appearance as a playable character in which game?"
answer = ["Super Mario Bros. 2"]

[[questions]]
question_type_id = "single_answer"
tags = ["video_games"]
[questions.detail]
text = "The Mario series character Toadsworth made their first appearance in which game?"
answer = ["Super Mario Sunshine", "Sunshine"]

[[questions]]
question_type_id = "single_answer"
tags = ["video_games"]
[questions.detail]
text = "Mario made his first appearance in which game?"
answer = ["Donkey Kong"]

[[questions]]
question_type_id = "single_answer"
tags = ["video_games"]
[questions.detail]
text = "The Mario series character Peach made their first appearance in which game?"
answer = ["Super Mario Bros.", "Super Mario Bros. 1"]

[[questions]]
question_type_id = "single_answer"
tags = ["video_games"]
[questions.detail]
text = "What game did Waluigi first appear in?"
answer = ["Mario Tennis"]

[[questions]]
question_type_id = "single_answer"
tags = ["video_games"]
[questions.detail]
text = "What is the name of the first Bowser level in Super Mario 64?"
answer = ["Bowser in the Dark World", "Dark World"]

[[questions]]
question_type_id = "single_answer"
tags = ["video_games"]
[questions.detail]
text = "In Super Mario Sunshine, a certain mission in what world must you complete before Yoshi is unlocked."
answer = ["Pinna Park"]

[[questions]]
question_type_id = "single_answer"
tags = ["video_games"]
[questions.detail]
text = "The name of your boat in The Legend of Zelda: Wind Waker is 'The King of Red ___'?"
answer = ["Lions"]

[[questions]]
question_type_id = "single_answer"
tags = ["video_games"]
[questions.detail]
text = "What game did Toadette first appear in?"
answer = ["Mario Kart: Double Dash", "MKDD", "Mario Kart Double Dash"]

[[questions]]
question_type_id = "single_answer"
tags = ["video_games"]
[questions.detail]
text = "What was the most recent game to feature Donkey Kong Jr. as a playable character?"
answer = ["Mario Tennis"]

[[questions]]
question_type_id = "single_answer"
tags = ["history"]
[questions.detail]
text = "What was the first city to reach a population of 1 million?"
answer = ["Rome"]

[[questions]]
question_type_id = "single_answer"
tags = ["video_games", "pokemon"]
[questions.detail]
text = "What fairy-type Pokemon has the highest base HP?"
answer = ["Wigglytuff"]

[[questions]]
question_type_id = "single_answer"
tags = ["video_games", "pokemon"]
[questions.detail]
text = "From Gen 3 onward, what were the color of the inside of a shiny Charizard's wings?"
answer = ["Red"]

[[questions]]
question_type_id = "single_answer"
tags = ["video_games", "pokemon"]
[questions.detail]
text = "Charizard was the inspiration for the name of 'Chilicola charizard', a species of what animal?"
answer = ["Bees"]

[[questions]]
question_type_id = "single_answer"
tags = ["video_games", "pokemon"]
[questions.detail]
text = "What is the only Pokemon whose base stat total does not change after evolution?"
answer = ["Scyther"]

