[[data]]
values = ["Mario", "Eggplant Man"]
answer = ["Wrecking Crew"]

[[data]]
values = ["Mario", "Shy Guy"]
answer = ["Super Mario Bros. 2"]

[[data]]
values = ["Mario", "Bob-omb"]
answer = ["Super Mario Bros. 2"]

[[data]]
values = ["Mario", "Dry Bones"]
answer = ["Super Mario Bros. 3]

[[data]]
values = ["Mario", "Boo"]
answer = ["Super Mario Bros. 3"]

[[data]]
values = ["Mario", "Chain Chomp"]
answer = ["Super Mario Bros. 3"]

[[data]]
values = ["Mario", "Paragoomba"]
answer = ["Super Mario Bros. 3"]

[[data]]
values = ["Mario", "Thwomp"]
answer = ["Super Mario Bros. 3"]

[[data]]
values = ["Mario", "Big Boo"]
answer = ["Super Mario World"]

[[data]]
values = ["Mario", "Wiggler"]
answer = ["Super Mario World"]

[[data]]
values = ["Mario", "Whomp"]
answer = ["Super Mario 64"]

[[data]]
values = ["Mario", "Koopa Kid"]
answer = ["Mario Party"]

[[data]]
values = ["Mario", "King Boo"]
answer = ["Luigi's Mansion"]

[[data]]
values = ["Mario", "Bowser Jr."]
answer = ["Super Mario Sunshine"]

[[data]]
values = ["Mario", "Wario"]
answer = ["Super Mario Land 2: 6 Golden Coins", "Super Mario Land 2"]


[template]
question_type_id = "single_answer"
tags = ["video_games"]
text = "The %s series character %s made their first appearance in which game?"


