[[data]]
values = ["Nintendo", "Banjo"]
answer = ["Diddy Kong Racing"]

[[data]]
values = ["Nintendo", "Conker"]
answer = ["Diddy Kong Racing"]

[template]
question_type_id = "single_answer"
tags = ["video_games"]
text = "The %s character %s made their first appearance in which game?"


