[[data]]
values = ["Mario", "Dry Bones"]
answer = ["Super Mario Bros. 3", "Super Mario Bros 3", "SMB3", "SMB 3"]


[template]
question_type_id = "single_answer"
tags = ["video_games"]
text = "The %s series character %s made their first appearance in which game?"


